'use strict';

const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');
const os = require('os');

const TMP_DIR = path.join(os.tmpdir(), 'rio-invoices');

function ensureTmp() {
  if (!fs.existsSync(TMP_DIR)) fs.mkdirSync(TMP_DIR, { recursive: true });
}

async function createInvoice({
  invoiceNumber,
  date,
  from: seller,
  to: buyer,
  items,
  currency = 'ILS',
  notes,
  taxRate = 17,
  language = 'he',
}) {
  ensureTmp();
  const outPath = path.join(TMP_DIR, `invoice_${invoiceNumber || Date.now()}.pdf`);

  const isHebrew = language === 'he';
  const currencySymbol = currency === 'ILS' ? '₪' : currency === 'USD' ? '$' : currency;

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50, layout: 'portrait' });
    const stream = fs.createWriteStream(outPath);
    doc.pipe(stream);

    doc.fontSize(24).text(isHebrew ? 'חשבונית' : 'INVOICE', { align: 'center' });
    doc.moveDown(0.5);

    doc.fontSize(10).text(`${isHebrew ? 'מספר' : '#'}: ${invoiceNumber || 'N/A'}`, { align: 'right' });
    doc.text(`${isHebrew ? 'תאריך' : 'Date'}: ${date || new Date().toLocaleDateString('he-IL')}`, { align: 'right' });
    doc.moveDown();

    doc.fontSize(11).text(isHebrew ? 'מאת:' : 'From:', { underline: true });
    doc.fontSize(10).text(seller?.name || 'N/A');
    if (seller?.address) doc.text(seller.address);
    if (seller?.phone) doc.text(seller.phone);
    if (seller?.email) doc.text(seller.email);
    doc.moveDown();

    doc.fontSize(11).text(isHebrew ? 'אל:' : 'To:', { underline: true });
    doc.fontSize(10).text(buyer?.name || 'N/A');
    if (buyer?.address) doc.text(buyer.address);
    if (buyer?.phone) doc.text(buyer.phone);
    if (buyer?.email) doc.text(buyer.email);
    doc.moveDown(1.5);

    const tableTop = doc.y;
    const colDesc = 50;
    const colQty = 350;
    const colPrice = 410;
    const colTotal = 480;

    doc.fontSize(10).font('Helvetica-Bold');
    doc.text(isHebrew ? 'פריט' : 'Item', colDesc, tableTop);
    doc.text(isHebrew ? 'כמות' : 'Qty', colQty, tableTop);
    doc.text(isHebrew ? 'מחיר' : 'Price', colPrice, tableTop);
    doc.text(isHebrew ? 'סה"כ' : 'Total', colTotal, tableTop);

    doc.moveTo(50, tableTop + 15).lineTo(550, tableTop + 15).stroke();
    doc.font('Helvetica');

    let y = tableTop + 25;
    let subtotal = 0;

    for (const item of (items || [])) {
      const qty = item.quantity || 1;
      const price = item.price || 0;
      const total = qty * price;
      subtotal += total;

      doc.text(item.description || 'Item', colDesc, y, { width: 290 });
      doc.text(String(qty), colQty, y);
      doc.text(`${currencySymbol}${price.toFixed(2)}`, colPrice, y);
      doc.text(`${currencySymbol}${total.toFixed(2)}`, colTotal, y);
      y += 20;
    }

    doc.moveTo(50, y).lineTo(550, y).stroke();
    y += 10;

    doc.text(`${isHebrew ? 'סכום ביניים' : 'Subtotal'}: ${currencySymbol}${subtotal.toFixed(2)}`, colPrice, y);
    y += 18;

    const tax = subtotal * (taxRate / 100);
    doc.text(`${isHebrew ? `מע"מ` : 'Tax'} (${taxRate}%): ${currencySymbol}${tax.toFixed(2)}`, colPrice, y);
    y += 18;

    const grandTotal = subtotal + tax;
    doc.font('Helvetica-Bold');
    doc.text(`${isHebrew ? 'סה"כ לתשלום' : 'Total'}: ${currencySymbol}${grandTotal.toFixed(2)}`, colPrice, y);
    doc.font('Helvetica');

    if (notes) {
      y += 40;
      doc.fontSize(9).text(`${isHebrew ? 'הערות' : 'Notes'}: ${notes}`, 50, y, { width: 500 });
    }

    doc.fontSize(8).text(
      isHebrew ? 'נוצר על ידי Rio — עוזר אישי בוואטסאפ' : 'Generated by Rio — WhatsApp Personal Assistant',
      50, 750, { align: 'center', width: 500 }
    );

    doc.end();
    stream.on('finish', () => resolve(outPath));
    stream.on('error', reject);
  });
}

module.exports = { createInvoice };
